### ISSUE TITLE
CopyAll fails on chmod for files

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#25]
Since current `cp` command in shell does not work recursively copying directories, and we should be consolidating those kinds of higher level FS operations into helpers that can eventually live in `toolkit-go`, I added a `CopyAll` to a new `fsutil` package with a temporary `cp2` command in shell. The `CopyAll` should be fine (ported from another project), but something about our FS stack is causing it to fail when using it in the environment.

To reproduce:
```
mkdir src
cd src
write file1 ONE
write file2 TWO
cd ..
cp2 src dst
```
Returns:
`chmod dst/file1: Operation not permitted`

It seems to make an empty file (not sure if it should be empty by then) but then the chmod operation fails. It's unclear where in our FS stack this is returned, but I'm guessing its mountablefs or indexedfs as opposed to between the shell runtime and the kernel.

This is probably not going to be fun to debug without fixing #24 first.

**Comment by Parzival-3141** [comment]
We're getting a `chmod` error because `indexedfs` doesn't support it yet.
https://github.com/tractordev/wanix/blob/e2add27dc5f89da98e141eeb29f06c884fae77d9/internal/indexedfs/indexedfs.go#L44-L46

This is pretty easy to fix, but requires some changes. Currently we only store the permission part of `FileMode` and a bool for `isdir`. We'd have to store the full `FileMode` in a `uint32` and adjust all `indexedfs` methods accordingly.
