### ISSUE TITLE
improve "build on run" UX for source commands

### ISSUE THREAD

**Issue by progrium** [tractordev/wanix#69]
We support "build on run" for commands implemented as Go source directories, but we get the output of the `build` compiler when its run. The `build` compiler should probably only output when there is a problem and leave the progress output behind a verbose flag. This would make "build on run" a more seamless experience.

**Comment by Parzival-3141** [comment]
As of https://github.com/tractordev/wanix/commit/214113a4584384f081a50820ed3dee4aab2b5155 this is "technically" complete, though only because all build output gets ignored in `proc.go`. AFAICT this is blocked by #64 since we don't have a good way of using stdio from within the kernel. In the meantime we could workaround this by piping `build`'s stdout/err to the browser console.

**Comment by progrium** [comment]
I recently set the default stdio for the kernel to be logged with console.log so this is good for now.
